### ISSUE TITLE
data loading error

### ISSUE THREAD

**Issue by yaoliUoA** [orsic/swiftnet#28]
I did not change the code. Got data loading error:

    trainer.train()
  File "train.py", line 115, in train
    for step, batch in batch_iterator:
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Tensors must have same number of dimensions: got 3 and 4 at /pytorch/aten/src/TH/generic/THTensor.cpp:603

**Comment by mailhoho** [comment]
I have the same error. Did you solve this error?

**Comment by hhhwww123** [comment]
> I did not change the code. Got data loading error:
> 
> ```
> trainer.train()
> ```
> 
> File "train.py", line 115, in train
> for step, batch in batch_iterator:
> File "/usr/local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in **next**
> data = self._next_data()
> File "/usr/local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
> return self._process_data(data)
> File "/usr/local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
> data.reraise()
> File "/usr/local/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
> raise self.exc_type(msg)
> RuntimeError: Caught RuntimeError in DataLoader worker process 0.
> Original Traceback (most recent call last):
> File "/usr/local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
> data = fetcher.fetch(index)
> File "/usr/local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
> return self.collate_fn(data)
> File "/usr/local/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate
> return {key: default_collate([d[key] for d in batch]) for key in elem}
> File "/usr/local/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 74, in 
> return {key: default_collate([d[key] for d in batch]) for key in elem}
> File "/usr/local/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
> return torch.stack(batch, 0, out=out)
> RuntimeError: invalid argument 0: Tensors must have same number of dimensions: got 3 and 4 at /pytorch/aten/src/TH/generic/THTensor.cpp:603

Hei,bro. I have the same error. Did you solve this error?
